feat: 채용 공고 생성 기능
채용 공고 생성 기능을 추가하였습니다.
CompaniesService의 findOneByCompanyId를 RecruitmentService에서 사용하기 위해 CompaniesModule과 RecruitmentModule을 수정했습니다.
Recruitment entity에서 recruit_compensation 타입을 string에서 number로 변경해주었습니다.

QueryFailedError: ER_NO_DEFAULT_FOR_FIELD: Field 'companyId' doesn't have a default value
위와 같은 에러가 발생합니다.

Resolve: #2
Ref: #2
Relate to: #2